language: node_js
node_js:
    - "4.0.0"
script: node_modules/karma/bin/karma start --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install